name: 05-manual run with inputs
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'target environment'
        required: true
        default: 'staging'
        type: choice
        option:
          - dev
          - staging
          - testing
          - production
      version:
        description: 'version to deploy (eg:1.4.0)'
        required: true
        default: 'latest'
        type: string
      dry_run:
        description: 'only simulate, don't actually deploy'
        required: false
        default: true
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: shows the inputs the user selected
        run: |
          echo "environment ${{inputs.environment}}"
          echo "version ${{inputs.version}}"
          echo "dry run: ${{inputs.dry_run}}"
        
      
          
