name: 06-scheduled run
on:
  schedule:
    - cron: '17 7 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: nightly housekeeping
        run:
          echo "run schedule job at $(date -u)"
