name: 06-scheduled run
on:
  workflow_dispatch:   # allows manual trigger for testing
  schedule:
    - cron: '30 7 * * *'   # runs daily at 07:30 UTC (1:00 PM IST)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: housekeeping
        run: echo "run schedule job at $(date -u)"
